### ISSUE TITLE
Res.g.cs generate illegal C#  name when there are dashes in the filename.

### ISSUE THREAD

**Issue by pcloves** [OlliO6/SafeStrings-GodotCS#2]
When there are dashes in the filename e.g., `angle-small-down.png`, the generated C# names are illegal e.g., `angle-small-down_png`. The `'-'` should be replaced to `'_'`.

``` C#
public static class Image
{
	public static readonly ResourcePath<Godot.CompressedTexture2D> angle-small-down_png = "res://addons/Behavior/Image/angle-small-down.png";
	public static readonly ResourcePath<Godot.CompressedTexture2D> angle-small-right_png = "res://addons/Behavior/Image/angle-small-right.png";
	public static readonly ResourcePath<Godot.CompressedTexture2D> cross_png = "res://addons/Behavior/Image/cross.png";
	public static readonly ResourcePath<Godot.CompressedTexture2D> plus_png = "res://addons/Behavior/Image/plus.png";
}
```

BTW, I'm working on my plugin using this fantastic plugin. I find that `addons` folder is excluded programmatically avoiding generate `ResourcePath`.  Do you think the `addons` folder is unnecessary?

**Comment by OlliO6** [comment]
Hey, I know kinda late response...
But anyways, thank you so much for contributing. Excides me a lot.
And you can actually set what resource paths will be ignored in the project settings, I just defaulted the addons folder to be ignore because I thought, You would't really need it in a game, but you can go to 'SafeStrings/resources/excluded_folers' in project settings and remove it from the list.

**Comment by OlliO6** [comment]
I realized, that this should actually be fixed after [this](https://github.com/OlliO6/SafeStrings-GodotCS/commit/4816fd019de38e459dac1883891a8551be02f687) commit, it changed quite a lot and also the way the `ConvertNameToCSName` method works.
